#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace stock_history
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="lucene")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertstock_trade_history(stock_trade_history instance);
    partial void Updatestock_trade_history(stock_trade_history instance);
    partial void Deletestock_trade_history(stock_trade_history instance);
    partial void Insertstock_id_name(stock_id_name instance);
    partial void Updatestock_id_name(stock_id_name instance);
    partial void Deletestock_id_name(stock_id_name instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::stock_history.Properties.Settings.Default.luceneConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<stock_trade_history> stock_trade_history
		{
			get
			{
				return this.GetTable<stock_trade_history>();
			}
		}
		
		public System.Data.Linq.Table<stock_id_name> stock_id_name
		{
			get
			{
				return this.GetTable<stock_id_name>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stock_trade_history")]
	public partial class stock_trade_history : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _stock_id;
		
		private string _stock_name;
		
		private string _kaipanjia;
		
		private string _zuigaojia;
		
		private string _soupanjia;
		
		private string _zuidijia;
		
		private string _jiaoyiliang;
		
		private string _jiaoyijine;
		
		private string _date;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onstock_idChanging(string value);
    partial void Onstock_idChanged();
    partial void Onstock_nameChanging(string value);
    partial void Onstock_nameChanged();
    partial void OnkaipanjiaChanging(string value);
    partial void OnkaipanjiaChanged();
    partial void OnzuigaojiaChanging(string value);
    partial void OnzuigaojiaChanged();
    partial void OnsoupanjiaChanging(string value);
    partial void OnsoupanjiaChanged();
    partial void OnzuidijiaChanging(string value);
    partial void OnzuidijiaChanged();
    partial void OnjiaoyiliangChanging(string value);
    partial void OnjiaoyiliangChanged();
    partial void OnjiaoyijineChanging(string value);
    partial void OnjiaoyijineChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    #endregion
		
		public stock_trade_history()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_id", DbType="NVarChar(50)")]
		public string stock_id
		{
			get
			{
				return this._stock_id;
			}
			set
			{
				if ((this._stock_id != value))
				{
					this.Onstock_idChanging(value);
					this.SendPropertyChanging();
					this._stock_id = value;
					this.SendPropertyChanged("stock_id");
					this.Onstock_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_name", DbType="NVarChar(50)")]
		public string stock_name
		{
			get
			{
				return this._stock_name;
			}
			set
			{
				if ((this._stock_name != value))
				{
					this.Onstock_nameChanging(value);
					this.SendPropertyChanging();
					this._stock_name = value;
					this.SendPropertyChanged("stock_name");
					this.Onstock_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kaipanjia", DbType="NVarChar(50)")]
		public string kaipanjia
		{
			get
			{
				return this._kaipanjia;
			}
			set
			{
				if ((this._kaipanjia != value))
				{
					this.OnkaipanjiaChanging(value);
					this.SendPropertyChanging();
					this._kaipanjia = value;
					this.SendPropertyChanged("kaipanjia");
					this.OnkaipanjiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zuigaojia", DbType="NVarChar(50)")]
		public string zuigaojia
		{
			get
			{
				return this._zuigaojia;
			}
			set
			{
				if ((this._zuigaojia != value))
				{
					this.OnzuigaojiaChanging(value);
					this.SendPropertyChanging();
					this._zuigaojia = value;
					this.SendPropertyChanged("zuigaojia");
					this.OnzuigaojiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soupanjia", DbType="NVarChar(50)")]
		public string soupanjia
		{
			get
			{
				return this._soupanjia;
			}
			set
			{
				if ((this._soupanjia != value))
				{
					this.OnsoupanjiaChanging(value);
					this.SendPropertyChanging();
					this._soupanjia = value;
					this.SendPropertyChanged("soupanjia");
					this.OnsoupanjiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zuidijia", DbType="NVarChar(50)")]
		public string zuidijia
		{
			get
			{
				return this._zuidijia;
			}
			set
			{
				if ((this._zuidijia != value))
				{
					this.OnzuidijiaChanging(value);
					this.SendPropertyChanging();
					this._zuidijia = value;
					this.SendPropertyChanged("zuidijia");
					this.OnzuidijiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jiaoyiliang", DbType="NVarChar(50)")]
		public string jiaoyiliang
		{
			get
			{
				return this._jiaoyiliang;
			}
			set
			{
				if ((this._jiaoyiliang != value))
				{
					this.OnjiaoyiliangChanging(value);
					this.SendPropertyChanging();
					this._jiaoyiliang = value;
					this.SendPropertyChanged("jiaoyiliang");
					this.OnjiaoyiliangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jiaoyijine", DbType="NVarChar(50)")]
		public string jiaoyijine
		{
			get
			{
				return this._jiaoyijine;
			}
			set
			{
				if ((this._jiaoyijine != value))
				{
					this.OnjiaoyijineChanging(value);
					this.SendPropertyChanging();
					this._jiaoyijine = value;
					this.SendPropertyChanged("jiaoyijine");
					this.OnjiaoyijineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stock_id_name")]
	public partial class stock_id_name : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _stock_name;
		
		private string _stock_type;
		
		private string _tag;
		
		private string _tag_date;
		
		private string _stock_id;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onstock_nameChanging(string value);
    partial void Onstock_nameChanged();
    partial void Onstock_typeChanging(string value);
    partial void Onstock_typeChanged();
    partial void OntagChanging(string value);
    partial void OntagChanged();
    partial void Ontag_dateChanging(string value);
    partial void Ontag_dateChanged();
    partial void Onstock_idChanging(string value);
    partial void Onstock_idChanged();
    #endregion
		
		public stock_id_name()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_name", DbType="NVarChar(50)")]
		public string stock_name
		{
			get
			{
				return this._stock_name;
			}
			set
			{
				if ((this._stock_name != value))
				{
					this.Onstock_nameChanging(value);
					this.SendPropertyChanging();
					this._stock_name = value;
					this.SendPropertyChanged("stock_name");
					this.Onstock_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_type", DbType="NVarChar(50)")]
		public string stock_type
		{
			get
			{
				return this._stock_type;
			}
			set
			{
				if ((this._stock_type != value))
				{
					this.Onstock_typeChanging(value);
					this.SendPropertyChanging();
					this._stock_type = value;
					this.SendPropertyChanged("stock_type");
					this.Onstock_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag", DbType="NVarChar(50)")]
		public string tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if ((this._tag != value))
				{
					this.OntagChanging(value);
					this.SendPropertyChanging();
					this._tag = value;
					this.SendPropertyChanged("tag");
					this.OntagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag_date", DbType="NVarChar(50)")]
		public string tag_date
		{
			get
			{
				return this._tag_date;
			}
			set
			{
				if ((this._tag_date != value))
				{
					this.Ontag_dateChanging(value);
					this.SendPropertyChanging();
					this._tag_date = value;
					this.SendPropertyChanged("tag_date");
					this.Ontag_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_id", DbType="NVarChar(50)")]
		public string stock_id
		{
			get
			{
				return this._stock_id;
			}
			set
			{
				if ((this._stock_id != value))
				{
					this.Onstock_idChanging(value);
					this.SendPropertyChanging();
					this._stock_id = value;
					this.SendPropertyChanged("stock_id");
					this.Onstock_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
